#Karaoke config \u2014 unknown - Usa-me, Renova-me com Tal Qual Estou
#Wed Mar 04 19:37:06 GMT-03:00 2026
audioExtension=opus
author=unknown
musicName=Usa-me, Renova-me com Tal Qual Estou
offsetSeconds=-0.2
realDurationMin=2.96
selectedVoice=0
