#Karaoke config \u2014 Steve Green - Abraça a Cruz Adaptado
#Tue Sep 08 05:24:13 GMT-03:00 2026
audioExtension=opus
author=Steve Green
musicName=Abra\u00E7a a Cruz Adaptado
offsetSeconds=0.45
realDurationMin=2.8380
selectedVoice=1
