#Karaoke config \u2014 Michael Smith - Agnus Dei
#Wed Sep 02 14:45:05 GMT-03:00 2026
audioExtension=opus
author=Michael Smith
musicName=Agnus Dei
offsetSeconds=4.00
realDurationMin=0.0000
selectedVoice=0
