#Karaoke config \u2014 Margem Norte - Além do Rio Azul
#Mon Jun 01 16:02:25 GMT-03:00 2026
audioExtension=opus
author=Margem Norte
musicName=Al\u00E9m do Rio Azul
offsetSeconds=1.57
realDurationMin=3.3570
selectedVoice=0
