#Karaoke config \u2014 Toronto Coral - Presente Lá do Céu
#Wed Mar 04 19:36:54 GMT-03:00 2026
audioExtension=opus
author=Toronto Coral
musicName=Presente L\u00E1 do C\u00E9u
offsetSeconds=0.3
realDurationMin=3.408
selectedVoice=3
