#Karaoke config \u2014 Coral do UNASP - Vinde Benditos
#Wed Mar 04 19:37:11 GMT-03:00 2026
audioExtension=opus
author=Coral do UNASP
musicName=Vinde Benditos
offsetSeconds=0.28
realDurationMin=4.0115
selectedVoice=0
