#Karaoke config \u2014 Vocal Livre - Quem de Nós
#Wed Mar 04 19:37:01 GMT-03:00 2026
audioExtension=opus
author=Vocal Livre
musicName=Quem de N\u00F3s
offsetSeconds=3.2
realDurationMin=4.8
selectedVoice=2
