#Karaoke config \u2014 Som e Louvor - O Lírio Ressurgiu
#Wed Mar 04 19:36:49 GMT-03:00 2026
audioExtension=opus
author=Som e Louvor
musicName=O L\u00EDrio Ressurgiu
offsetSeconds=2.9
realDurationMin=4.7
selectedVoice=0
