#Karaoke config \u2014 Som e Louvor - O Lírio Ressurgiu
#Sat Mar 07 16:12:03 GMT-03:00 2026
audioExtension=opus
author=Som e Louvor
musicName=O L\u00EDrio Ressurgiu
offsetSeconds=2.90
realDurationMin=4.7000
selectedVoice=3
