#Karaoke config \u2014 Prisma Brasil - Meu Lar
#Thu Mar 05 22:35:55 GMT-03:00 2026
audioExtension=opus
author=Prisma Brasil
musicName=Meu Lar
offsetSeconds=1.80
realDurationMin=4.5920
selectedVoice=2
