#Karaoke config \u2014 Prisma Brasil - Meu Lar
#Wed Mar 04 19:36:42 GMT-03:00 2026
audioExtension=opus
author=Prisma Brasil
musicName=Meu Lar
offsetSeconds=1.8
realDurationMin=4.595
selectedVoice=2
