#Karaoke config \u2014 Prisma Brasil - Agradece ao Pai
#Fri Mar 06 08:53:26 GMT-03:00 2026
audioExtension=opus
author=Prisma Brasil
musicName=Agradece ao Pai
offsetSeconds=13.00
realDurationMin=3.0520
selectedVoice=2
