#Karaoke config \u2014 Prisma Brasil - Agradece ao Pai
#Wed Mar 04 19:30:07 GMT-03:00 2026
audioExtension=opus
author=Prisma Brasil
musicName=Agradece ao Pai
offsetSeconds=13.0
realDurationMin=3.06
selectedVoice=2
