#Karaoke config \u2014 Prisma Brasil - Agradece ao Pai
#Thu Mar 05 08:39:39 GMT-03:00 2026
audioExtension=opus
author=Prisma Brasil
musicName=Agradece ao Pai
offsetSeconds=13.00
realDurationMin=3.055
selectedVoice=0

