#Karaoke config \u2014 Cantata Experiência com Deus - Usa-me, Renova-me com Tal Qual Estou
#Sat May 30 06:42:06 GMT-03:00 2026
audioExtension=opus
author=Cantata Experi\u00EAncia com Deus
musicName=Usa-me, Renova-me com Tal Qual Estou
offsetSeconds=-0.20
realDurationMin=2.9190
selectedVoice=2
