#Karaoke config \u2014 Nova Voz - Enquanto Eu Viver
#Wed Sep 02 13:08:19 GMT-03:00 2026
audioExtension=opus
author=Nova Voz
musicName=Enquanto Eu Viver
offsetSeconds=3.05
realDurationMin=4.7849
selectedVoice=0
