#Karaoke config \u2014 Steve Green - Abraça a Cruz
#Mon Sep 07 09:00:31 GMT-03:00 2026
audioExtension=opus
author=Steve Green
musicName=Abra\u00E7a a Cruz
offsetSeconds=0.00
realDurationMin=0.0000
selectedVoice=0
