#Karaoke config \u2014 Nova Voz - Digno é o Senhor
#Thu Mar 05 22:33:58 GMT-03:00 2026
audioExtension=opus
author=Nova Voz
musicName=Digno \u00E9 o Senhor
offsetSeconds=2.00
realDurationMin=5.0620
selectedVoice=3
