#Karaoke config \u2014 Nova Voz - Digno é o Senhor
#Sun Feb 22 21:06:06 BRT 2026
audioExtension=opus
name=Nova Voz - Digno \u00E9 o Senhor
offsetSeconds=1.8
realDurationMin=5.070000000000001
selectedVoice=3
